name: Liberdus TSS Secret Scan

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: "0 3 * * 1"

permissions:
  contents: read

jobs:
  trufflehog-verified:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.95.5
        with:
          path: ./
          base: ${{ github.event_name == 'pull_request' && github.base_ref || github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified --exclude-paths=.github/trufflehog-exclude-paths.txt

  trufflehog-full-history:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS Full Scan
        uses: trufflesecurity/trufflehog@v3.95.5
        with:
          path: ./
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --exclude-paths=.github/trufflehog-exclude-paths.txt
